dotnet user-secrets set "ServiceBusConnectionString" "add your connection string here"
dotnet user-secrets set "ServiceBusQueueName" "myqueue"
dotnet user-secrets set "ServiceBusTopicName" "demo-topic"
dotnet user-secrets set "ServiceBusSubscriptionName" "demo-subscription"
dotnet user-secrets set "DataLakeConnectionString" "add your connection string here"
dotnet user-secrets set "DataLakeContainerName" "my-file-system"
dotnet user-secrets set "DataLakeFileName" "demo-file"
dotnet user-secrets set "DataLakeFolderName" "my-folder"
dotnet user-secrets set "SubDirectoryName" "my-subdirectory"
dotnet user-secrets set "Directory" "my-directory"
dotnet user-secrets set "FolderName" "my-folder"
