name: Trigger auto deployment for mvp-app-worker

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/mvp-app-worker-AutoDeployTrigger-392a2099-3b72-41d0-85c7-85054cdf310e.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      #substitute production appsettings entries to appsettings json file
      - name: App Settings Variable Substitution
        uses: microsoft/variable-substitution@v1
        with:
          files: '${{env.DOTNET_ROOT}}/myapp/appsettings.json'
        env:
          ConnectionStrings.ServiceBusConnectionString: ${{ secrets.SERVICEBUS_CONNECTION_STRING }}
          ConnectionStrings.DataLakeConnectionString: ${{ secrets.DATALAKE_CONNECTION_STRING }}
          App.ServerRootAddress: ${{ env.SERVER_ROOT_ADDRESS }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: timotacr.azurecr.io
          username: ${{ secrets.MVPAPPWORKER_REGISTRY_USERNAME }}
          password: ${{ secrets.MVPAPPWORKER_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: timotacr.azurecr.io/mvp-app-worker:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MVPAPPWORKER_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n mvp-app-worker -g my-container-apps --server timotacr.azurecr.io --username  ${{ secrets.MVPAPPWORKER_REGISTRY_USERNAME }} --password ${{ secrets.MVPAPPWORKER_REGISTRY_PASSWORD }}
            az containerapp update -n mvp-app-worker -g my-container-apps --image timotacr.azurecr.io/mvp-app-worker:${{ github.sha }}
